language: java
jdk:
  - openjdk8

branches:
  only:
    - main

sudo: required

cache:
  directories:
    - '$HOME/.target'

services:
  - docker

before_install:
  - echo "start build business work"

#  - docker run -e CI=true

after-success:
  - docker build -t eddydocdoc/business-frontend ./docker/vue
  - docker build -t eddydocdoc/business-backend ./docker/spring

#  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
#
#  - docker push eddydocdoc/business-backend
#  - docker push eddydocdoc/business-frontend