language: java
jdk:
  - openjdk8

sudo: required

services:
  - docker

before_install:
  - echo "start build business work"
  - docker build -t eddydocdoc/business-backend -f ./docker/spring/Dockerfile .

script:
  - docker run -e CI=true eddydocdoc/business-backend

after-success:
  - docker build -t eddydocdoc/business-frontend ./docker/vue/Dockerfile .

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push eddydocdoc/business-backend
  - docker push eddydocdoc/business-frontend